language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: X16bLe26ru8zfojECgpGPbGekhUfQkFUILr4u6Gi3xQgj9mjHRvukPxve8/CEKpCuhGXCWbVpJrTJQfBHzWSdO0OHZ9ZnG3tUR6jVVHRSJ56TEBwcz0FJAaO7B+NbGJjNfWNIGoq1mejK6Au2+flQkmO4y7xrKA/rfkGSf+yA5Hlqbe5ADUHGgbd97q6XwPVtyQ5WpzivFG9KzXFDARvJfeaO6ARr6D1eMAaNotmsscxzEvEFTJ4CqjFPei29xuMWTPkNWyRHrDn6WrUy/8e0shSR7FTiiHbNZXP0g3B/y1L8Uvgxal4vfDPq9uSAv/AtNOn+Exhbg15xh7I/MrwRKc3JH5SEH6c17h8hpRtA8e6QrcybPfOnaBn01FpbC8gUB8IU3MjdvZEl8n4xoaHeJyldcbQ9V0qCpWNeaNLLNIR7Kk1j+qr71zmKgvFxv1tA2t1++H6ywvWOoSSEqu4qDDHyODuPzvgJRSWIon2WCqXaDPJV4sSYxFGbcB1FbWoVg9Sxwja4ZbHb2gLvMh7j31mqZ2PPBQml7NWnN5wHw9xUHT5HFK/8e4M4ee2vPmSAR4RDcBb5cKc2c7tdvdPwDgorFjfkYF0x14JTTwicJqdUF3NLiku7st3Gd1fkuI/C3GPManZZd50piF7oCOSKN0uyp6XiYEEbwyudstrh44=
  app: radiant-fortress-87765
  on:
    repo: Btan579/CI-hot-cold
