language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: QP9vZUeMlR5keRDdwf4H4RiWPfyp5xoe6C2cBx5PM0gSbi9qy1yF/BVdIDO5IJkE+8v2LjbwQFHtrOtmI4d2VqMdmJX2dcsyMD9dgy6iNxZYFhGvUo0hot0e1H6pu+BFTjF8MZvPtfo+BG1zzS/VGdFbCn8nG3azGt14vwAIprjoZu0BX6aBaR4bjcGLPbDha/S3RgMl7it8aZgFfRwyxPqOUzRB1/2p5tTxOTnGkQ8NS182rDJKdbjweGDQT272tQtQaEypM5iyQYT+7tTVVjgQt7AiSLqhye4q7RyHefhItvz96UtJdXSzKgR92HQwZda0Mz/q/KaBwfTVe37BQiPJQr8Bp/zM99/De4OosdMwBJEfquvqPIEGFoJubmjfRlmR85/lHtaFxH1kBTQjq+EPBJIJKJDFIonDaQcpXv+4t7iyfhCTX9bVtS47EwWQ6vpjU/2GH3iuiwrVAO+/H+rJHYNRCz8Gh0BgH3IUKX3OtbeT99uP8F5Tciq1vSsXjz3Ev+bz/68ZOu5n1p3JzBuTuNGfD5kfGd1R/Y80jSV7jv/onYMDp345GcNURZfwLJogoS5LN1e4EtXPeV3Q75psQLVQCkoD6fzI5QSrhV1JZ6cQ2qP4bDRjddPP7RWJ/kXpAGogt/1tEi/6pzZrQGPdnW1aoELbZN3Ek3hO2rA=
  app: radiant-fortress-87765
  on:
    repo: Btan579/CI-hot-cold


